### ISSUE TITLE
Installing pyheif on Mac and getting 'libheif/heif.h' file not found error.

### ISSUE THREAD

**Issue by yyaqoob** [carsales/pyheif#27]
i try to install pyheif on Mac from pip/pip3 and getting 'libheif/heif.h' file not found error.

ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/vr/v6k80qzx0dqb0s3wgtt7dgdw0000gn/T/pip-install-aV1cwO/pyheif/setup.py'"'"'; __file__='"'"'/private/var/folders/vr/v6k80qzx0dqb0s3wgtt7dgdw0000gn/T/pip-install-aV1cwO/pyheif/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/vr/v6k80qzx0dqb0s3wgtt7dgdw0000gn/T/pip-record-7FR4TT/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/vr/v6k80qzx0dqb0s3wgtt7dgdw0000gn/T/pip-install-aV1cwO/pyheif/
    Complete output (23 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-2.7
    creating build/lib.macosx-10.9-x86_64-2.7/pyheif
    copying pyheif/error.py -> build/lib.macosx-10.9-x86_64-2.7/pyheif
    copying pyheif/constants.py -> build/lib.macosx-10.9-x86_64-2.7/pyheif
    copying pyheif/__init__.py -> build/lib.macosx-10.9-x86_64-2.7/pyheif
    copying pyheif/reader.py -> build/lib.macosx-10.9-x86_64-2.7/pyheif
    copying pyheif/writer.py -> build/lib.macosx-10.9-x86_64-2.7/pyheif
    running build_ext
    generating cffi module 'build/temp.macosx-10.9-x86_64-2.7/_libheif_cffi.c'
    creating build/temp.macosx-10.9-x86_64-2.7
    building '_libheif_cffi' extension
    creating build/temp.macosx-10.9-x86_64-2.7/build
    creating build/temp.macosx-10.9-x86_64-2.7/build/temp.macosx-10.9-x86_64-2.7
    gcc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c build/temp.macosx-10.9-x86_64-2.7/_libheif_cffi.c -o build/temp.macosx-10.9-x86_64-2.7/build/temp.macosx-10.9-x86_64-2.7/_libheif_cffi.o
    build/temp.macosx-10.9-x86_64-2.7/_libheif_cffi.c:493:15: fatal error: 'libheif/heif.h' file not found
         #include "libheif/heif.h"
                  ^~~~~~~~~~~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/vr/v6k80qzx0dqb0s3wgtt7dgdw0000gn/T/pip-install-aV1cwO/pyheif/setup.py'"'"'; __file__='"'"'/private/var/folders/vr/v6k80qzx0dqb0s3wgtt7dgdw0000gn/T/pip-install-aV1cwO/pyheif/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/vr/v6k80qzx0dqb0s3wgtt7dgdw0000gn/T/pip-record-7FR4TT/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by coxevan** [comment]
Same error here on Windows 10 this morning

**Comment by david-poirier-csn** [comment]
Mac OS is supported, but you have to follow the instructions in the README.md

Windows is not supported.

**Comment by yyaqoob** [comment]
Hi David.
pyheif required python 3.6+ and i have installed python version 3.7.3.
i try to install pyheif from "pip install git+https://github.com/david-poirier-csn/pyheif.git" as mentioned in README.md but getting above error. Can you guid if i am doing some thing wrong. 
Thanks
