### ISSUE TITLE
Exif medatada

### ISSUE THREAD

**Issue by liriarte** [carsales/pyheif#29]
I am following your readme to convert to jpg and it works. However; it does not seem to write the exif metadata. Once the JPG is saved to disk, the following line fails:

`Image.open(file)._getexif().items()`

How can I also write the exif metadata to the new JPG file?

**Comment by david-poirier-csn** [comment]
This is more of a Pillow issue but I'll try to point you in the right direction - you need to pass an `exif` param containing the raw EXIF data to the `save` method of the Pillow image, as noted here - https://pillow.readthedocs.io/en/3.0.x/handbook/image-file-formats.html#jpeg

This is of course ridiculous but that's how it works.
