### ISSUE TITLE
Add trivial path to allow Macports users to build pyheif with pip

### ISSUE THREAD

**Issue by jiawen** [carsales/pyheif#32]
I use MacPorts instead of Homebrew. `sudo port install libheif` puts everything under `/opt/local` instead of `/usr/local`.

I can confirm that `pip install --global-option=build_ext --global-option="-I/opt/local/include/" --global-option="-L/opt/local/lib" pyheif` works.

Can we add `-I/opt/local/include/` and `L/opt/local/lib` to `libheif_build.py` [here](https://github.com/carsales/pyheif/blob/658b10fa671dadaac00031de96bd818a9d2920ee/libheif/libheif_build.py#L15-L17)?

**Comment by jiawen** [comment]
It'd be nice to also add MacPorts instructions in `README.md`. Do you prefer a PR?

**Comment by david-poirier-csn** [comment]
Yes pls, PR
