### ISSUE TITLE
Problem installing pyheif on Python 3.9

### ISSUE THREAD

**Issue by vincentwoo** [carsales/pyheif#34]
I think I'm having some issue with CFFI installying pyheif. Here's a very simple dockerfile that reproduces my issue:

```
FROM ubuntu:18.04
RUN apt-get update
RUN apt-get install -y python3.8 python3-pip libffi-dev libheif-dev libde265-dev
RUN pip3 install pyheif
```

and here's the build log: [log.txt](https://github.com/carsales/pyheif/files/5543169/log.txt)

**Comment by david-poirier-csn** [comment]
The dependencies are probably out of date - you should be able to install the binary wheel on ubuntu - try doing `pip3 install wheel` before `pip3 install pyheif`

**Comment by david-poirier-csn** [comment]
Scratch that, I think you just need to update pip first - `pip3 install --upgrade pip`

**Comment by vincentwoo** [comment]
That did it. I was trying to reproduce errors installing on Heroku with an aptfile on their ubuntu 18 stack, but clearly I need to do more work. I'll maybe be back, thanks so much.

**Comment by vincentwoo** [comment]
Ah, it seems the problem stemmed from not being able to download a precompiled wheel? Here's a repro using the debian python 3.9.0 base image (since it seemed like my problem was due to using 3.9.0 on heroku):

```
FROM python:3.9.0-buster
RUN apt-get update
RUN apt-get install -y libffi-dev libheif-dev libde265-dev
RUN pip install pyheif
```

yielding: [log.txt](https://github.com/carsales/pyheif/files/5543384/log.txt)

**Comment by david-poirier-csn** [comment]
Make sure you run `pip install --upgrade pip` first - the wheels are made according to the `manylinux2014` standard, which requires a very recent `pip`

**Comment by vincentwoo** [comment]
Ya, 3.9.0-buster comes with the latest pip. The issue is the wheel is missing: https://pypi.org/project/pyheif/#files, wheels are only compiled up to cp38 at the moment

**Comment by david-poirier-csn** [comment]
Ah, well in that case you can either run 3.8, install the dependencies from source, or wait until a 3.9 wheel is built.

**Comment by vincentwoo** [comment]
Sure, reasonable enough. Do you have some sense for why pyheif installation fails? I'm surprised one would have to, say, compiled libffi from source (if that's the problem).

**Comment by david-poirier-csn** [comment]
It'll be libheif (or possible but probably not libde265) that needs to be installed from source, not libffi. The current pyheif release probably wants libheif 1.7.0 - https://github.com/strukturag/libheif/releases/tag/v1.7.0

**Comment by vincentwoo** [comment]
Thanks, will keep an eye out.
