### ISSUE TITLE
I think I cannot install this on my M1 chip mac

### ISSUE THREAD

**Issue by fyenne** [carsales/pyheif#35]
1 error generated.
 error: command 'gcc' failed with exit status 1
  ----------------------------------------
 ERROR: Failed building wheel for pyheif

Is it my problem?

**Comment by david-poirier-csn** [comment]
Not sure as I don't have Apple silicon. Is that the entire error message?

**Comment by panosangelopoulos** [comment]
Same here, the gcc command is failing.

```
#10 321.6     gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include -I/usr/include -I/usr/local/include/python3.8 -c build/temp.linux-aarch64-3.8/_libheif_cffi.c -o build/temp.linux-aarch64-3.8/build/temp.linux-aarch64-3.8/_libheif_cffi.o
#10 321.6     build/temp.linux-aarch64-3.8/_libheif_cffi.c: In function ‘_cffi_const_heif_unknown_brand’:
```

**Comment by guillaumegenthial** [comment]
I faced the same issue, https://github.com/carsales/pyheif/pull/45 seems to resolve it.
