### ISSUE TITLE
Installing via pip on mac results in 'libheif/heif.h' file not found fatal error

### ISSUE THREAD

**Issue by skyleguy** [carsales/pyheif#36]
hello, trying to do some image processing on my images. Unfortunately iPhones switched to using heic files sometime recently and now all of my newer images are heic. I am already using the PILLOW library so i was happy when i saw this library that adds heic use to pillow:

https://pypi.org/project/pyheif-pillow-opener/

However when i install it using pip:

pip3 install pyheif-pillow-opener i get an error. After running through the dependencies of this i got to this library, pyheif, and tried running:

pip3 install pyheif only to get this:

```
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/usr/local/include -I/usr/include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c build/temp.macosx-10.9-x86_64-3.9/_libheif_cffi.c -o build/temp.macosx-10.9-x86_64-3.9/build/temp.macosx-10.9-x86_64-3.9/_libheif_cffi.o
    build/temp.macosx-10.9-x86_64-3.9/_libheif_cffi.c:570:15: fatal error: 'libheif/heif.h' file not found
         #include "libheif/heif.h"
                  ^~~~~~~~~~~~~~~~
    1 error generated.
    error: command '/usr/bin/gcc' failed with exit code 1
```

is there any way to fix this issue? I can't seem to open any heic files with python until i can resolve this. Thank you!

**Comment by j3pup** [comment]
Same thing on windows today.

**Comment by david-poirier-csn** [comment]
On macOS - install `brew` (https://brew.sh) then `brew install libheif`

On Windows - use macOS or Linux instead
