### ISSUE TITLE
Is it possible to add `manylinux1` wheel  packages? 

### ISSUE THREAD

**Issue by bigcat88** [carsales/pyheif#46]
Good project, works fine and great. Thanks you for your work.
We install it without admin permissions, and on Ubuntu all is fine, it install from binaries, but on Debian 10 with pip 18.1 it ask for package with manylinux1 tag, and there is no one.
Is it possible to add that tag to support installation with using binaries, without building it from sources? 

Thanks you anyway, we appreciate you for your work!

**Comment by piaobuliao** [comment]
change filename from “pyheif-0.5.1-cp36-cp36m-manylinux2014_x86_64.whl”
to “pyheif-0.5.1-cp36-cp36m-manylinux1_x86_64.whl”
maybe works
