### ISSUE TITLE
Commit history is blowed up

### ISSUE THREAD

**Issue by homm** [carsales/pyheif#60]
The bunch of last PR was merged in strange way, so each next commit contain changes from the previous step. This is really hard to understand what exactly was merged and how correct it was. In particular, this is how [this conflict](https://github.com/carsales/pyheif/commit/00d0ffb0c0e777a4e9b3d12580649f3a5d8d9723) was introduced.

## Solution
Rollback everything. Reset master to the last correct commit which is https://github.com/carsales/pyheif/commit/04d513b8183c49fd9f1ea7305f3fbd1943796ee4. Then apply PR in the following order: 

1. https://github.com/carsales/pyheif/pull/61
2. https://github.com/carsales/pyheif/pull/62
3. https://github.com/carsales/pyheif/pull/64
4. https://github.com/carsales/pyheif/pull/50
5. https://github.com/carsales/pyheif/pull/63
6. https://github.com/carsales/pyheif/pull/67
7. https://github.com/carsales/pyheif/pull/68
8. https://github.com/carsales/pyheif/pull/66
9. https://github.com/carsales/pyheif/pull/65

**Importtant**: wait for resolving conflicts in PR, not try to fix this silently.

@ant32bit-carsales Are you agree?

**Comment by ant32bit-carsales** [comment]
Will you be willing to help again if I do this?

**Comment by homm** [comment]
You need completely accept PR open source culture. You can see [how worst things going](https://github.com/carsales/pyheif/commit/b315a619b2e64748f8df6c6391fe59ff3a644c33) with current style of development. Don't make any changes in master, review every change in PR. 

I can be willing to help if I can control you, unless I can't control this repository.

**Comment by ant32bit-carsales** [comment]
Apart from perhaps the wording, I can accept this. I will do the PRs in the order suggested about. I've blocked out my whole day tomorrow to work on this.

**Comment by homm** [comment]
I can recreate all this PRs. As far as I know there is no way to reopen already merged PRs.

**Comment by ant32bit-carsales** [comment]
Probably not needed, I can still fetch them as branches from git cli

**Comment by homm** [comment]
You can fetch, but please don't resolve any conflicts on your side, all conflicts should be resolved in branches before merging.

**Comment by ant32bit-carsales** [comment]
Ah, I see. OK that's where I went wrong. OK. Then yes, please recreate them, I'll do that from now on.

**Comment by homm** [comment]
Let's start with the first five. I rearrange it slightly and included https://github.com/carsales/pyheif/pull/50 fix.

**Comment by ant32bit-carsales** [comment]
Those five have been merged. Thanks for taking the time to go through this. David and I had never owned an open source project before this one and I haven't really had a lot of experience with the culture myself. I'm glad to learn it, so I really appreciate your stepping me through this.

**Comment by homm** [comment]
I am really really glad to hear this! Now the commit history and merge commits are all looks great! Thank you for this.

I've prepared the next 4 commits and updated the list. The actual order doesn't matter anymore.

I suppose there will be conflicts in `test_read.py` module after the first merges, this is OK, just leave a comment if you notice this and the author of PR (me) will fix it by rebasing or by merging fresh `master` back in the branch.

**Comment by homm** [comment]
Yeeeeah! Resolved )

**Comment by ant32bit-carsales** [comment]
Thanks for your patience. This was way easier this time round. I'm going to wait till I can source a Windows and M1 Mac and get through the rest. 

I've also been building some interest with a few of people in carsales and we're going to start working on some of the features requested, particularly reading non-primary images and writing heif files. 

It's been really great working with you, after getting off on the wrong foot. Thanks again.
