### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by homm** [carsales/pyheif#70]
There are some changes in `master` made since the latest 0.6.0 release. Some of them already used in [heif-image-plugin](https://pypi.org/project/heif-image-plugin/). Will be cool to see a new release.

**Comment by homm** [comment]
@ant32bit-carsales ?

**Comment by ant32bit-carsales** [comment]
Just realised I hadn’t released the latest today. I’m gonna do it tomorrow.

**Comment by ant32bit-carsales** [comment]
0.6.1 released
