### ISSUE TITLE
Python 3.11 wheel support

### ISSUE THREAD

**Issue by sshishov** [carsales/pyheif#80]
Can we have the package for python 3.11 as a wheel?

Otherwise we are getting this message during build:
```bash
building '_libheif_cffi' extension
creating build/temp.linux-x86_64-cpython-311/build
creating build/temp.linux-x86_64-cpython-311/build/temp.linux-x86_64-cpython-311
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include -I/usr/include -I/opt/local/include -I/home/wafeq/venv/include -I/usr/local/include/python3.11 -c build/temp.linux-x86_64-cpython-311/_libheif_cffi.c -o build/temp.linux-x86_64-cpython-311/build/temp.linux-x86_64-cpython-311/_libheif_cffi.o
build/temp.linux-x86_64-cpython-311/_libheif_cffi.c: In function ‘_cffi_const_heif_suberror_Wrong_tile_image_pixel_depth’:
build/temp.linux-x86_64-cpython-311/_libheif_cffi.c:1761:12: error: ‘heif_suberror_Wrong_tile_image_pixel_depth’ undeclared (first use in this function); did you mean ‘_cffi_const_heif_suberror_Wrong_tile_image_pixel_depth’?
 1761 |   int n = (heif_suberror_Wrong_tile_image_pixel_depth) <= 0;
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |            _cffi_const_heif_suberror_Wrong_tile_image_pixel_depth
build/temp.linux-x86_64-cpython-311/_libheif_cffi.c:1761:12: note: each undeclared identifier is reported only once for each function it appears in
build/temp.linux-x86_64-cpython-311/_libheif_cffi.c: In function ‘_cffi_d_heif_image_handle_is_premultiplied_alpha’:
build/temp.linux-x86_64-cpython-311/_libheif_cffi.c:5529:10: warning: implicit declaration of function ‘heif_image_handle_is_premultiplied_alpha’; did you mean ‘_cffi_d_heif_image_handle_is_premultiplied_alpha’? [-Wimplicit-function-declaration]
 5529 |   return heif_image_handle_is_premultiplied_alpha(x0);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |          _cffi_d_heif_image_handle_is_premultiplied_alpha
error: command '/usr/bin/gcc' failed with exit code 1
```

Please note that `libheif-dev` and `libde265-dev` are installed. The library `libffi` could not be found on the server (Debian)

**Comment by DrMeers** [comment]
getting the same issue on Python 3.9 and Python 3.10, using `python:3.9-slim`, `python:3.10-slim` and also tried `python:3.11-slim` docker images, even with `libffi-dev` and `libheif-dev` installed -- it seems the `heif.h` version is much older and doesn't contain lines like https://github.com/strukturag/libheif/blob/master/libheif/heif.h#L212 and https://github.com/strukturag/libheif/blob/master/libheif/heif.h#L1562 (which were added two years ago apparently), thus resulting in the above two errors

```
# apt show libheif-dev
Package: libheif-dev
Version: 1.11.0-1

# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

**Comment by stadnitski** [comment]
@sshishov @DrMeers had exactly the same problem having `libheif-dev` version `1.11`. 

SOLVED upgrading `libheif-dev` version `1.12` or `1.13`.

**Comment by DrMeers** [comment]
Unfortunately `libheif-dev` is only currently available in version `1.11.0-1` in [stable Debian releases](https://packages.debian.org/bullseye/libheif-dev)

**Comment by DrMeers** [comment]
I'm able to compile against `libheif-dev` version `1.11.0-1` using https://github.com/carsales/pyheif/compare/master...DrMeers:pyheif:1.11

**Comment by sshishov** [comment]
I guess the new version with Python3.11 wheel support has been released. Thanks.

Just a aside note, we have moved to this library: https://github.com/bigcat88/pillow_heif
