### ISSUE TITLE
New release which works with current libheif

### ISSUE THREAD

**Issue by scorpi11** [carsales/pyheif#96]
Hi,

I want to include pyheif in Debian. However, it looks like the latest release is old and does not work with the current libheif. Would you mind to make a release which I can use to create a pyheif package? Of cause, I can also use some git revision, but the packaging workflow requires more manual steps and is more error prone.

**Comment by homm** [comment]
Could you try to install from the following branch:

```bash 
$ pip install git+https://github.com/uploadcare/pyheif.git@read-transformations
```
